### ISSUE TITLE
switch to using the spring cloud BOM?

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/spring-cloud-kubernetes#46]
I recently ported a hystrix sample over to [use the spring cloud bom](https://github.com/fabric8-quickstarts/spring-boot-hystrix/blob/master/pom.xml#L56-L62) to simplify the dependencies [like this](https://github.com/fabric8-quickstarts/spring-boot-hystrix/blob/master/pom.xml#L77-L90).

When I tried this on the spring-boot-ribbon example I got all kinds of version clashes (see below). It'd be nice if we switched to just using a spring cloud BOM (and keeping it in sync with the property in [fabric8-maven-dependencies](https://github.com/fabric8io/fabric8-maven-dependencies/blob/master/pom.xml#L70) so that its easier to keep quickstarts + spring-cloud-kubernetes and kubeflix in sync with the spring cloud versions?

Here's the clashes with spring-cloud-kubernetes and spring-cloud BOM:
```
[INFO] --- spring-boot-maven-plugin:1.4.0.RELEASE:run (default-cli) @ spring-boot-ribbon ---
[WARNING]
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.boot.maven.AbstractRunMojo$LaunchRunner.run(AbstractRunMojo.java:483)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.commons.util.InetUtils.<init>(Lorg/springframework/cloud/commons/util/InetUtilsProperties;)V
	at org.springframework.cloud.client.HostInfoEnvironmentPostProcessor.getFirstNonLoopbackHostInfo(HostInfoEnvironmentPostProcessor.java:48)
	at org.springframework.cloud.client.HostInfoEnvironmentPostProcessor.postProcessEnvironment(HostInfoEnvironmentPostProcessor.java:34)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:168)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:154)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:140)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:62)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:121)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:335)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at io.fabric8.quickstarts.ribbon.Application.main(Application.java:32)
	... 6 more
```

**Comment by christian-posta** [comment]
didn't see this issue before submitting my PR.. @jstrachan think https://github.com/fabric8io/spring-cloud-kubernetes/pull/47 fixes this?

**Comment by jstrachan** [comment]
Ah cool! Wonder if we can remove any more versions from the pom.xml like these: https://github.com/fabric8io/spring-cloud-kubernetes/blob/master/pom.xml#L87-L88

**Comment by christian-posta** [comment]
yah, missed those. will clean up.

**Comment by christian-posta** [comment]
https://github.com/fabric8io/spring-cloud-kubernetes/pull/48

**Comment by jstrachan** [comment]
think we can say this is fixed now, thanks @christian-posta
