### ISSUE TITLE
Unable to get Config Map configuration

### ISSUE THREAD

**Issue by andrewrutter** [fabric8io/spring-cloud-kubernetes#76]
I am trying to deploy a sample application to a managed K8 cluster but am having trouble getting configuration working using ConfigMaps. When my test service starts I am seeing the following error in the logs "Error while establishing a connection to watch config maps" which I can see in the code but am not sure what might be the root cause. My service is falling back to some default configuration and nothing is being picked up at runtime and certainly not if the ConfigMap values are changed.

What is a good way to trace this through as everything seems to be wired up correctly? Thanks in advance

**Comment by micrump** [comment]
That is the exception stacktrace for the issue:
````
io.fabric8.kubernetes.client.KubernetesClientException: Error while establishing a connection to watch config maps: configuration may remain stale
    at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onFailure(WatchConnectionManager.java:194)
    at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:543)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:185)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
````
